apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: helm-dot-ai-stack
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/hops-ops/helm-dot-ai-stack
    meta.crossplane.io/description: Installs DevOps AI Toolkit Stack (dot-ai) Helm chart.
spec:
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: ">=v1.0.2"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
