apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: helm-dot-ai-stack
spec:
  package: ghcr.io/hops-ops/helm-dot-ai-stack:{{ .Values.version }}
{{- if .Values.skipDependencyResolution }}
  skipDependencyResolution: true
{{- end }}
{{- if .Values.skipDependencyResolution }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: hops-ops-helm-dot-ai-stackrender
spec:
  package: ghcr.io/hops-ops/helm-dot-ai-stack-render:{{ .Values.version }}
{{- end }}
